; cyberfox1337x.function("agefield_uue4ss_settings")
[Overrides]
ModsFolderPath =

[General]
EnableHotReloadSystem = 0
UseCache = 1
InvalidateCacheIfDLLDiffers = 1
SecondsToScanBeforeGivingUp = 30
bUseUObjectArrayCache = true

[EngineVersionOverride]
MajorVersion =
MinorVersion =

[ObjectDumper]
LoadAllAssetsBeforeDumpingObjects = 0

[CXXHeaderGenerator]
DumpOffsetsAndSizes = 0
KeepMemoryLayout = 0
LoadAllAssetsBeforeGeneratingCXXHeaders = 0

[UHTHeaderGenerator]
IgnoreAllCoreEngineModules = 1
IgnoreEngineAndCoreUObject = 1
MakeAllFunctionsBlueprintCallable = 0
MakeAllPropertyBlueprintsReadWrite = 0
MakeEnumClassesBlueprintType = 0
MakeAllConfigsEngineConfig = 0

[Debug]
ConsoleEnabled = 0
GuiConsoleEnabled = 0
GuiConsoleVisible = 0
GuiConsoleFontScaling = 1
GraphicsAPI = opengl
LiveViewObjectsPerGroup = 32768

[Threads]
SigScannerNumThreads = 8
SigScannerMultithreadingModuleSizeThreshold = 16777216

[Memory]
MaxMemoryUsageDuringAssetLoading = 80

[Hooks]
HookProcessInternal = 1
HookProcessLocalScriptFunction = 0
HookInitGameState = 1
HookCallFunctionByNameWithArguments = 0
HookBeginPlay = 0
HookLocalPlayerExec = 0
FExecVTableOffsetInLocalPlayer = 0x28

[CrashDump]
EnableDumping = 0
FullMemoryDump = 0

[ExperimentalFeatures]
GUIUFunctionCaller = 0
